[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
notan = "0.13.0"

rand = "0.9.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ewebsock = "0.4"

shared = { path = "../shared" }
